### ISSUE TITLE
Please update for Gnome 40, and 41

### ISSUE THREAD

**Issue by thilomaurer** [bananenfisch/RecentItems#11]

**Comment by thilomaurer** [comment]
Actually, you did for 40.
It just the updated version is not available via extensions.gnome.org.

**Comment by thilomaurer** [comment]
Is the updated extension stuck in the review process?

**Comment by bananenfisch** [comment]
shame on me (i'm still on gnome 3.38 - debian freeze). for v40 its now online on extensions.gnome.org... v41 needs to be reviewed (normally it takes 2-3 days). but you can test it for gnome 41 (metadata already changed at github)...

**Comment by bananenfisch** [comment]
both 40 and 41 are now online on extensions.gnome.org
