### ISSUE TITLE
Does not list applications?

### ISSUE THREAD

**Issue by AtomicStick** [bananenfisch/RecentItems#12]
Looking at the extension.js it lists "application" as a file type, but recently opened applications do not show up for me. Is this expected behavior and I'm misinterpreting the types of recent items that can be listed?

**Comment by bananenfisch** [comment]
The "application/*" mime-type is not an application itself, but the file of an application. For example "application/pdf" refers to an PDF document (not to a pdf viewer). The "recently-used"-list in gnome stores always only the files (but not which applications were opened).
