### ISSUE TITLE
Push GNOME42 Update to/extensions.gnome.org

### ISSUE THREAD

**Issue by InklingGirl** [bananenfisch/RecentItems#14]
Please push your GNOME42 update to https://extensions.gnome.org/extension, as the version on there right now is incompatible. Thank you!

**Comment by sr258** [comment]
@bananenfisch This would be really helpful!

**Comment by skurzinz** [comment]
+1 even if it’s easy to just update the extension file locally :)

**Comment by bananenfisch** [comment]
oops sorry, i forgot... now its done ;-)
