### ISSUE TITLE
Add support for Gnome 44

### ISSUE THREAD

**Issue by forteller** [bananenfisch/RecentItems#17]
Hi. I've been using your extension for a long time, and it's one of my true must haves. A real time saver! So I'm saddened that it does not have support for Gnome 44 yet. If you have the time to update it, that would make me happy. Thank you so much for your work!

**Comment by bonjour81** [comment]
Hello,

As a workaround, until it's pushed to gnome extension website site:  I followsed the path of extension.js specified in https://github.com/bananenfisch/RecentItems/blob/master/README.md

in same folder, I edited metadata.json to add version 44 below 43, reboot, that's it !
so in my case it was: 
`nano ~/.local/share/gnome-shell/extensions/[RecentItems@bananenfisch.net](mailto:RecentItems@bananenfisch.net)/metadata.json
`
as you can see, the extension itself seems to not have changed for years, only gnome version number to be added in metadata => just a personnal guess, I know nothing about extension design.

you can also see metadata.json on github is already ready for version 44 but maybe was not pushed to https://extensions.gnome.org/

**Comment by forteller** [comment]
Thank you very much!

**Comment by bananenfisch** [comment]
Sorry - i've pushed it to extensions.gnome now.

**Comment by joseantoniosa** [comment]
Same error, I have gnome-shell : 44.5-2 (Debian unstable)
How could I debug this essential extensions.
Thanks in advance!

**Comment by bananenfisch** [comment]
> Same error, I have gnome-shell : 44.5-2 (Debian unstable) How could I debug this essential extensions. Thanks in advance!

Do you have an error message? I'm also on Debian unstable (44.5-1) - the latest version should work.
Any messages from "journalctl | grep RecentItems"?

**Comment by joseantoniosa** [comment]
JS ERROR: Extension RecentItems@bananenfisch.net: Error: Requiring Gtk, version 3.0: Requiring namespace 'Gtk' version '3.0', but '4.0' is already loaded
                                          @/home/jantonio/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:31:13
                                          _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:478:13
                                          async*loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:394:33
                                          _onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:294:35
                                          Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:130:41
May be I have a problem with gir1.2-gtk-3.0 and gir1.2-gtk-4.0, both are installed.

**Comment by bananenfisch** [comment]
The version for gnome 45 should fix this issue?
