### ISSUE TITLE
gnome 45

### ISSUE THREAD

**Issue by andrew-fader-discovery** [bananenfisch/RecentItems#19]
Gnome 45 has some changes to imports because of the new js version

**Comment by molitona** [comment]
@andrew-fader-discovery you got it fixed?

**Comment by BlankParticle** [comment]
I have added Gnome 45 Support.
See #20 for PR

Download the built extension [here](https://github.com/BlankParticle/RecentItems-gnome/releases/tag/gnome-45)

**Comment by molitona** [comment]
> I have added Gnome 45 Support. See #20 for PR
> 
> Download the built extension [here](https://github.com/BlankParticle/RecentItems-gnome/releases/tag/gnome-45)

works perfectly, thanks @BlankParticle

**Comment by bananenfisch** [comment]
todo: upload to extensions.gnome.org

**Comment by bananenfisch** [comment]
upload done
