### ISSUE TITLE
Alterar a quantidade mínima e máxima de históricos.

### ISSUE THREAD

**Issue by pablo-hp** [bananenfisch/RecentItems#21]
Poderia ter uma opção para escolher a quantidade máxima de históricos armazenados.

**Comment by bananenfisch** [comment]
I do not speak spanish.
translate.google.com

**Comment by skurzinz** [comment]
is eh portugues :)

**Comment by skurzinz** [comment]
OP wants to have options for setting min and max number of history entries. 

… Which is set in the `item count` variables in `/schemas/org.gnome.shell.extensions.recent-items.gschema.xml#L6` apparently.

**Comment by bananenfisch** [comment]
Ah, Shorti?! Como vai? Que bom ler de você novamente :) Quer uma cerveja?
