### ISSUE TITLE
Agrupar arquivos recentes por tipo de extensão do arquivo

### ISSUE THREAD

**Issue by pablo-hp** [bananenfisch/RecentItems#23]
poderia ter uma opção de agrupar ou não, os arquivos recentes, por tipo de extensão do arquivo.
Exemplo: Imagens, Audios, Textos, Arquivos Compactados, etc....

**Comment by bananenfisch** [comment]
I do not speak spanish.
translate.google.com

**Comment by pablo-hp** [comment]
desculpo a sua falta de inteligência.
