### ISSUE TITLE
Gnome 46 Not working 

### ISSUE THREAD

**Issue by Sidethorn** [bananenfisch/RecentItems#24]
Not working under gnome 46 and can you please add option to delete not needed items straight from the extension, like it did https://extensions.gnome.org/extension/977/recent-items. Thanks

**Comment by molitona** [comment]
@Sidethorn 
did y found a solution ?
even editing metadata.json by replacing it with gnome 46 didn't work for me!

**Comment by molitona** [comment]
@bananenfisch

**Comment by bananenfisch** [comment]
I run debian sid (unstable) and debian stable systems - debian sid is still on gnome 44.9. They are busy to do the big t64 transition (https://wiki.debian.org/ReleaseGoals/64bit-time).

I do not have enough resources to setup a VM with the latest gnome just 2 weeks after every release just for testing and fixing. So, just wait: when gnome 46 arrives debian sid, i will fix it.

Or: just help me ;-)
Any error messages would be great!

**Comment by molitona** [comment]
ok, i'm on arch.
tell me what to do and i'll reply to u

**Comment by bananenfisch** [comment]
What's the output of `journalctl | grep -i recentitems`
Maybe the fix is simple.

**Comment by molitona** [comment]
in gnome extension app i get this error shown in a popup

TypeError: this.add_actor is not a function

![s](https://github.com/bananenfisch/RecentItems/assets/35532337/311fbf53-79bf-4ee0-a8f9-ccf97207e428)


the out of the cmd is as below

```
_launchFile@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:161:11
                                           _sync/<@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:122:18
                                           _launchFile@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:161:11
                                           _sync/<@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:122:18
Apr 04 17:45:50 Unknown gnome-shell[11498]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                              RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                              enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
                                            The offending signal was destroy on Gjs_RecentItems_bananenfisch_net_extension_RecentItems 0x64e012ba0c60.
Apr 04 18:00:26 Unknown gnome-shell[17852]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                              RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                              enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
                                            The offending signal was destroy on Gjs_RecentItems_bananenfisch_net_extension_RecentItems 0x5b1ca8352410.
Apr 04 18:01:32 Unknown gnome-shell[19813]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                              RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                              enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
                                            The offending signal was destroy on Gjs_RecentItems_bananenfisch_net_extension_RecentItems 0x61e22c170900.
Apr 04 18:10:31 Unknown gnome-shell[24036]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                              RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                              enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
                                            The offending signal was destroy on Gjs_RecentItems_bananenfisch_net_extension_RecentItems 0x59a149955900.
Apr 04 18:11:50 Unknown gnome-shell[26047]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                              RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                              enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
                                            The offending signal was destroy on Gjs_RecentItems_bananenfisch_net_extension_RecentItems 0x611d4462ed40.
Apr 04 18:36:10 Unknown gnome-shell[98636]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                              RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                              enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
                                            The offending signal was destroy on Gjs_RecentItems_bananenfisch_net_extension_RecentItems 0x60e5d53cb050.
Apr 04 18:40:34 Unknown gnome-shell[101226]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                               RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                               enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
Apr 05 18:05:18 Unknown gnome-shell[3556]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                             RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                             enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
Apr 05 18:15:03 Unknown gnome-shell[9192]: Extension RecentItems@bananenfisch.net: TypeError: this.add_actor is not a function
                                             RecentItems@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:68:12
                                             enable@file:///home/user/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:28:16
```

**Comment by molitona** [comment]
as to per https://github.com/bmwiedemann/openSUSE/blob/13c1179cab4f21925e453e039e04d9174e286d7a/packages/h/hamster-time-tracker/0174-Fix-compatibility-issues-with-Gnome-shell-46.patch#L4

replaced this.add_actor by this.add_child on line 68 and now got other error -> this.box.add is not a function

**Comment by molitona** [comment]
i fixed it @bananenfisch !!

**Comment by molitona** [comment]
i'll create a PR

**Comment by molitona** [comment]
I noticed that i made a PR with the modified version of @BlankParticle 

gnome 46 patch is just replacing (add_actor) and (add) methods by (add_child)

for a reason i dunno it didn't work with @BlankParticle and don't have time to debug

so i put the zip of the old version which works perfect on gnome 46 with the applied patch

[RecentItems@bananenfisch.net.zip](https://github.com/bananenfisch/RecentItems/files/14895222/RecentItems%40bananenfisch.net.zip)

**Comment by bananenfisch** [comment]
That's great! Thx for fixing :)
I have the changes in the latest release: https://github.com/bananenfisch/RecentItems/releases

If this version works on gnome 46, i'll upload to extensions.
Any feedback welcome...

(I hope, debian will update gnome soon for maintaining without installing VMs in the future ;))

**Comment by BlankParticle** [comment]
Hey, sorry I was not able to work on this, I kinda suspected this. I am currently not using gnome, and setting up a gnome VM to test the extension was pain. Most extensions worked with just the metadata, but I had to change this function in my extensions too.

Glad you got it fixed

**Comment by molitona** [comment]
> That's great! Thx for fixing :) I have the changes in the latest release: https://github.com/bananenfisch/RecentItems/releases
> 
> If this version works on gnome 46, i'll upload to extensions. Any feedback welcome...
> 
> (I hope, debian will update gnome soon for maintaining without installing VMs in the future ;))

thank u, yeah it works perfectly!

**Comment by molitona** [comment]
> Hey, sorry I was not able to work on this, I kinda suspected this. I am currently not using gnome, and setting up a gnome VM to test the extension was pain. Most extensions worked with just the metadata, but I had to change this function in my extensions too.
> 
> Glad you got it fixed

thanks which DE u currently use?

**Comment by Sidethorn** [comment]
Thanks everybody it works perfectly.

**Comment by molitona** [comment]
> Thanks everybody it works perfectly.

very happy to help

**Comment by InklingGirl** [comment]
Hey, if the fix is working, when will it be pushed to https://extensions.gnome.org/extension/72/recent-items/ @bananenfisch? The latest LTS release of Ubuntu will be coming out w/ GNOME 46 this month, so it would be great to have in time for the launch.

**Comment by Sidethorn** [comment]
will this working release ever make it into the gnome shell extension page?

**Comment by molitona** [comment]
@InklingGirl @Sidethorn 
replace extensions.js  in ~/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net with the one i mentioned then logout+login

**Comment by bananenfisch** [comment]
finally... should be on extensions.gnome.org after review.

**Comment by InklingGirl** [comment]
not yet it ain't, must be pending still
