### ISSUE TITLE
Recent items sorted from old to new

### ISSUE THREAD

**Issue by verthezp** [bananenfisch/RecentItems#26]
In the current version (I'm on Gnome 46), the most recent item shows up at the bottom of the list instead of at the top.  At first I even thought that new recent items were not added, but after I cleared the list I saw new ones indeed listed, but in the opposite order that I expected.    So once the list contains the maximum number of items it will not show new items anymore.

**Comment by paulgir** [comment]
I am also seeing this behaviour on Gnome 46

**Comment by bananenfisch** [comment]
Fixed in the latest version here (should be on extensions.gnome.org after review).
