### ISSUE TITLE
Missing Margins

### ISSUE THREAD

**Issue by thilomaurer** [bananenfisch/RecentItems#4]
2 visual deficiencies:

* There is no margin between the icons and the filenames.
* Files without an icon are displayed out of grid.

![image](https://user-images.githubusercontent.com/5707738/29858245-ed556552-8d5c-11e7-99bc-3f92f1261673.png)

I'm running Fedora 25 with gnome 3.22.2

**Comment by bananenfisch** [comment]
Generally, is there still no fork of this? Thought, its dead... but it seems. Well, i try to solve these bugs until christmas...would also be great, if another dev can helps... so this could be that, was it was...

**Comment by bananenfisch** [comment]
quick but ok: now there is a whitespace between... should be fixed now.
