### ISSUE TITLE
Open containing folder?

### ISSUE THREAD

**Issue by orschiro** [bananenfisch/RecentItems#5]
Hey @bananenfisch,

Love your extension, thanks so much for it!

Could we add an option to open the containing folder that an item resides in?

This would be super useful to get to the context of a file!

Thanks so much! :-)

**Comment by sxc731** [comment]
Note (in case this helps): the Gnome "Files" app offers this functionality as a right-click on elements in the "Recent" folder.  

IMHO this opens all manner of useful use-cases (eg: being able to rename a file or open it with a different app) at little additional expense.

**Comment by orschiro** [comment]
> IMHO this opens all manner of useful use-cases (eg: being able to rename a file or open it with a different app) at little additional expense.

True good point! Perform a right mouse click on a file from the recent files list and perform any kind of those actions. Like it. :-) 

Is there an API we could rely on?

**Comment by bananenfisch** [comment]
demokritos wrote a patch for this: right click opens the containing folder.
is now in version 16.

**Comment by orschiro** [comment]
Thanks, nice! 👋🙂

-
