### ISSUE TITLE
Error: Tried to construct an object without a GType

### ISSUE THREAD

**Issue by ghost** [bananenfisch/RecentItems#8]
Install Manjaro Gnome 3.36.1
After install I see this warning and error:
`dub 22 05:56:02 zbook gnome-shell[4749]:   inflating: /home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js
dub 22 05:56:02 zbook gnome-shell[4749]:  extracting: /home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/metadata.json
dub 22 05:56:02 zbook gnome-shell[1322]: Usage of object.actor is deprecated for RecentItems
                                         get@resource:///org/gnome/shell/ui/environment.js:287:29
                                         _init@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:69:5
                                         enable@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:171:9
                                         _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:165:32
                                         loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:335:26
                                         callback@resource:///org/gnome/shell/ui/extensionDownloader.js:220:39
                                         gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
dub 22 05:56:02 zbook gnome-shell[1322]: Usage of object.actor is deprecated for RecentItems
                                         get@resource:///org/gnome/shell/ui/environment.js:287:29
                                         _init@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:70:5
                                         enable@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:171:9
                                         _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:165:32
                                         loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:335:26
                                         callback@resource:///org/gnome/shell/ui/extensionDownloader.js:220:39
                                         gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
dub 22 05:56:02 zbook gnome-shell[1322]: JS ERROR: Extension RecentItems@bananenfisch.net: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject>
                                         MyPopupMenuItem@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:46:5
                                         _display@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:106:24
                                         _init@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:73:10
                                         enable@/home/lorenc/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/extension.js:171:9
                                         _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:165:32
                                         loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:335:26
                                         callback@resource:///org/gnome/shell/ui/extensionDownloader.js:220:39
                                         gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13`

**Comment by bananenfisch** [comment]
Are you using version 17 or the new version 18?
