### ISSUE TITLE
Gnome 40

### ISSUE THREAD

**Issue by skurzinz** [bananenfisch/RecentItems#9]
… shows "OUTDATED" in extensions.gnome.org. Any chance this will be ported?

**Comment by bananenfisch** [comment]
Yes, it will be updated after next Debian release (Summer?) - the rolling testing/unstable distribution is freezed (with gnome 3.38) until next release. Maybe it works with Gnome 40? You could try to change the metadata.json (~/.local/share/gnome-shell/extensions/RecentItems\@bananenfisch.net/metadata.json) to hit the "shell-version". Or wait for Debian :D

**Comment by skurzinz** [comment]
> Maybe it works with Gnome 40? You could try to change the metadata.json (~/.local/share/gnome-shell/extensions/RecentItems@bananenfisch.net/metadata.json) to hit the "shell-version". 

Yep, you were right (together with e.g. https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/). Just bumping the version to `shell-version = [ "40" ]` indeed did the trick. Thx for the quick reply!

**Comment by bananenfisch** [comment]
Thx for testing! I'll upload the version for Gnome 40 to the extension site :-)
